---
- name: "Create backend application directory"
  file:
    path: ~/backend-application
    state: directory

- name: "Unzip backend files"
  unarchive:
    src: backend-artifact.tar.gz
    dest: ~/backend-application
    
- name: "Start Node app using PM2"
  shell: |
    cd ~/backend-application/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save
