---
  - name: "Package upgrade"
    become: true
    package:
      upgrade: true

  - name: "install packages"
    become: true
    package:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: true

 - name: "install n"
    become: true
    npm:
      name: n
      global: true
      production: true

  - name: "install correct nodejs version: 13.8.0"
    become: true
    shell: n 13.8.0

  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: true
      production: true
      state: present 
